### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/infogas03#2]
Coloquem aqui as discussões sobre planos e bugs.
Marquem milestones.
Marquem tags.
Abram, discutam, fechem, usem e abusem.

**Comment by tonyfrance** [comment]
boa noite
É para colocar o system "pause".?

**Comment by wesleysilas** [comment]
Boa noite professor, 
está todo mundo com uma dúvida em comum... por dia, são em média 3 a 4 commits por grupo ou por pessoa? 
temos quase certeza que é por grupo, só estou confirmando com o senhor! 
abraço!

**Comment by wesleysilas** [comment]
GALERA!!! ATENÇAO!!!
Estamos comentando os bugs e erros na pasta "Comente mais no programa", onde deveriam ser feitos esse comentários aqui!!! 
:/

**Comment by tonyfrance** [comment]
master atualizado.

**Comment by wirlany** [comment]
GALERINHA, Já que vamos trazer a discussão sobre Bugs para esse fórum... (do "Discutir mais" para cá)
Ao executar o programa INFOGAS.C, nós ( EU, SILAS, THIAGO e ANTONIO) percebemos um bug na hora de mostrar a sequência de paradas, ele pulava da primeira para última.

**Comment by wesleysilas** [comment]
Após o grupo(EU, WIRLANY, THIAGO E ANTONIO) discutir, 
chegamos à conclusão que foi um erro no laço... ele estava fechando antes da função acabar.

**Comment by wesleysilas** [comment]
ATENÇÃO! Havia um Bug que foi detectado, onde na parte final do programa, quando o programa perguntava se era a última parada, estava apenas imprimindo na tela e não estávamos conseguindo responder a tal pergunta. Após horas de estudos, conseguimos(EU, THIAGO E ANTONIO) corrigir esse erro. O meu commit " CORREÇOES NO PROGRAMA" coloquei o programa com esse bug corrigido...

**Comment by tonyfrance** [comment]
Galera no final da última parada ele perguntava "último abastecimento ?" Poderiamos trocar para "última parada?" Oque vocês acham.

**Comment by wesleysilas** [comment]
acho melhor, porque não temos como calcular ao certo quanto vai durar esse último abastecimento...
se não der nenhum problema na execução...

**Comment by thiagooqueiroz** [comment]
Acredito q não tony pq no caso se o motorista vai querer colocar mais um abastecimento já iria ser para  mais uma parada ...

**Comment by thiagooqueiroz** [comment]
Gente ao final da viagem no programa , ao indicar o tempo de viagem ele apenas mostra o 1.5 vazio ....não era para ser : tempo de viagem = 1.5 ????? e pode ser tanto 1.5 ou 1h 30 min ????

**Comment by wesleysilas** [comment]
Consegui ajeitar Thiago!!! 
era uma linha a mais que tinha... retirei e coloquei um "printf" para aparecer a frase "temo final" e coloquei também unidade "h" que tava faltando. 
Esse problema foi solucionado no meu ultimo commit.

**Comment by tonyfrance** [comment]
Ok tiago, ok silas o master foi atualizado,  desculpem o erro

**Comment by wesleysilas** [comment]
Pessoal, estou percebendo uma falha no nosso programa INFOGAS.C no finalzinho dele...
ele não está calculando direito o consumo total... apenas está dividindo o valor percorrido total pelo abastecido na última parada. Quando na verdade era pra estar dividindo o valor total a ser percorrido pelo total de gasolina gasta. Além disso, Tem um Bug que está deixando o Consumo total Negativo. 
estou trabalhando aqui pra ver se ajeito, qualquer coisa, falo a vocês... olhem aí também!

**Comment by wesleysilas** [comment]
Acabei de consertar o problema do consumo negativo no programa em C... porém, falta ajeitar o calculo do consumo, pois está calculando errado. Não consegui ajeitar isso, por isso que dei Commit só com o ajuste de sinal, para que vocês possam tentar solucionar o problema desse cálculo. 
Vamos lá pessoal... Falta pouco!

**Comment by wesleysilas** [comment]
Gabriel tinha consertado o consumo negativo nas linhas 70 por ai... mas ainda sim o consumo final  tava negativo pois ele esqueceu de colocar a variável no fim também... la pelas linhas 100 e pouco. observem ai!

**Comment by tonyfrance** [comment]
O silas eu vi ontem q  a distância e dividida por 4 ( nao tenho certeza)da uma olhada aew

**Comment by wesleysilas** [comment]
beleza...
estou tentando ajustar o calculo no final do INFOGAS.C
e no INFOGAS.GPT o programa ja está pronto... só faltam alguns últimos e mínimos ajustes...

**Comment by tonyfrance** [comment]
estou tento um problema para atualizar mas ja estou resolvendo.

**Comment by tonyfrance** [comment]
ok dei um reset no meu develop, caso voces queiram saber (git rest --hard nome do local a ser resetado)

**Comment by tonyfrance** [comment]
conseguimos(Eu, Silas, Gabriel) consertar o calculo do consumo médio final.
introduzimos uma variável "cof" para calcular a media dos consumos.

**Comment by wesleysilas** [comment]
Belezaaa! Programa em C 99,9999% finalizado. Falta só uns últimos ajustes de estética, mas nada que interfira mais na execução do programa.

Agora, falta só o finzinho do GPT também.

**Comment by tonyfrance** [comment]
ok, falta pouco

**Comment by wesleysilas** [comment]
Terminamos...
Obrigado pessoal que participou. 
o professor criou o grupo infogas3 com 10 pessoas, não tivemos a responsabilidade de todos presente na elaboração do programa, mas mesmo assim conseguimos concluir. 
valeu! 
amanhã tentarei terminar nossa Wiki.

**Comment by tonyfrance** [comment]
terminamos, obrigado silas e demais colegas que nos ajudaram, verdade silas, mas tenho a consciência de que ainda fui atras para fazerem o programa conosco, todos aqui já são homens e mulheres sabem das suas responsabilidades.

**Comment by wesleysilas** [comment]
justamente isso Antonio!!!!

**Comment by wesleysilas** [comment]
ACABEI DE FAZER NOSSA WIKI....
VEJAM AÍ. ACHEI BEM LEGAL, ESPERO QUE TENHAM GOSTADO!
Obrigado!

**Comment by tonyfrance** [comment]
ok silas, ficou bom parabens

**Comment by wirlany** [comment]
Ficou muito bom Silas..  👏👏
