### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by drbeco** [tonyfrance/infogas03#4]
Não fazer fork.

Todos vão trabalhar no repositório ORIGINAL (tonyfrance/infogas03)

Fork só irá confundir e não será considerado!

Corrijam, apaguem os forks. (edited, typo)

**Comment by gabrielgou** [comment]
Corrigido!

**Comment by wirlany** [comment]
Ok Professsor, já apaguei e refiz sem o Fork.

**Comment by thiagooqueiroz** [comment]
Já corrigido !

**Comment by wesleysilas** [comment]
Apaguei também e o refiz corretamente!
