### ISSUE TITLE
Começar as Tags!

### ISSUE THREAD

**Issue by gabrielgou** [tonyfrance/infogas03#5]
Na modificações significativas do programa devemos sair colocando as Tags, lembrando que até hj 15/09 devemos já colocar tag V0.1, e as seguintes estão no Milestone para nos basearmos, até dia 20/09 que é a entrega, colocaremos a tag v1.0 e o programa funcional.

**Comment by tonyfrance** [comment]
Ok

**Comment by wesleysilas** [comment]
tranquilo!

**Comment by wirlany** [comment]
ok!

**Comment by thiagooqueiroz** [comment]
tag V0.1 já foi criada.

**Comment by tonyfrance** [comment]
ok thiago.
