### ISSUE TITLE
Comentar mais no programa!

### ISSUE THREAD

**Issue by gabrielgou** [tonyfrance/infogas03#7]
Pessoal, tentem comentar mais no programa pois ele vai auxiliar outro programador que for modificar o programa de onde você parou.

**Comment by japds** [comment]
lembrar que portugol é diferente  de prolog

**Comment by thiagooqueiroz** [comment]
que comentário pertinente, JAPDS... legal!

**Comment by wesleysilas** [comment]
No meu segundo commit de hoje  "Adição de bibliotecas e mais linhas", fui até a introduçao do parâmetros de hora.

**Comment by gabrielgou** [comment]
lembrem-se em C para comentar no programa é
ex:
//escreva aqui seu comentario na linha.
duas barras você pode comentar na minha e tudo que escrever não influenciará no código, é meramente para ajudar até você mesmo quando outra pessoa a entender melhor o código.

e pode também utilizar o : /\* .... */

ex:

/\* meu comentario
pode ultrapassar as linhas e só 
vai fechar com */

**Comment by wesleysilas** [comment]
GENTE! 
Apaguei o programa antigo pois estava fora dos parâmetros que o professor exigiu ( com umas funções avançadas/strings e structs que não devíamos usar). Essas funções iam nos atrapalhar no desenvolvimento do programa em GPT. 
Já dei um novo commit adicionando as bibliotecas! Continuem! Abraço!!!

**Comment by wesleysilas** [comment]
GENTE! 
Apaguei o programa (em C) antigo pois estava fora dos parâmetros que o professor exigiu ( com umas funções avançadas/strings e structs que não devíamos usar). Essas funções iam nos atrapalhar no desenvolvimento do programa em GPT. 
Já dei um novo commit adicionando as bibliotecas! Continuem! Abraço!!!

**Comment by wirlany** [comment]
Ok, tbm já comecei a editar o infogas.c para o correto.

**Comment by tonyfrance** [comment]
acrescentei mais uns printf's e scanf's sobre a primeira parada

**Comment by tonyfrance** [comment]
galera, tinha uns caracteres estranhos no infogas.gpt 

# " <<<<<<<<<<< HEAD

> > > 134245&¨2542"

**Comment by thiagooqueiroz** [comment]
gente o programa esta com erros ao compilar !!!!
consegui solucionar dois ....mas ainda tem !
hoje temos que finalizar o programa em c para começarmos em gpt ....

**Comment by tonyfrance** [comment]
ok tiago estou no servidor, ja estou vendo o erro

**Comment by tonyfrance** [comment]
tiago concertei um erro, tinha uma variavel não declarada.

**Comment by tonyfrance** [comment]
galera silas tirou o ultimo erro de compilação . mas ocorre um bug no programa , onde não avisa na ultima parada o 1-sim e o 0-não e no ultimo abastecimento aparece 1-sim/n, onde não deveria aparecer esse /n mas sim pular uma linha .

**Comment by wirlany** [comment]
Certo estou no servidor tbm e vou tentar alterar o programa pra tirar esse erro

**Comment by wesleysilas** [comment]
Não pulou uma linha, pois a barra tá pra o lado errado... aí apareceu esse /n como uma palavra normal... 
Vou tentar consertar agora...

**Comment by tonyfrance** [comment]
galera tinha um erro de copilação, pois a variavel estava errada mudei de gi para a gn que é a certa.

**Comment by wesleysilas** [comment]
ACABEI DE FAZER NOSSA WIKI....
VEJAM AÍ. ACHEI BEM LEGAL, ESPERO QUE TENHAM GOSTADO!
Obrigado!
