### ISSUE TITLE
Finalização do programa.

### ISSUE THREAD

**Issue by gabrielgou** [tonyfrance/infogas03#9]
E para completar nossa meta devemos terminar completamente o programa até dia 20/09, 
ou seja correção de bugs que ainda estejam no programa em C e finalização do programa em Gportugol. Quais bugs vocês viram que ainda permanecem ou pontos de otimização para o programa?

**Comment by tonyfrance** [comment]
no .c, tem quando ele chega na terceira para o consumo de combustivel fica "infkm/l "
o consumo da negativo, a hora de viagem da certa mas as parcias nao. so vi esses to tentando ajeitar e vou vendo se tem mais

**Comment by tonyfrance** [comment]
programa em C finalizado fiz o ajuste no calculo do consumo medio  junto com silas e gabriel, atualizem o develop e teste para conferir se ta tudo nos conformes.
